name: 'Xcode Export Archive'
description: 'Export a product from an archive'

branding:
  icon: 'command'
  color: 'blue'

inputs:
  workspace:
    description: 'Workspace'
    required: false
  project:
    description: 'Project'
    required: false
  scheme:
    description: 'Scheme'
    required: false

  archive-path:
    description: 'Archive path. If not specified will default to MainScheme.xcarchive'
  export-method:
    description: "Export method (development, developer-id). Defaults to developer-id."
    default: "developer-id"
  export-path:
    description: "Path where the exported product will be put. Defaults to Export."
    default: "Export"

runs:
  using: 'node12'
  main: 'dist/index.js'

